### PR TITLE
add some membership info

### PR DESCRIPTION
**Pull request by BertHartm**

### CODE REVIEW

**Comment by BertHartm** [comment]
@eabraham mind proof reading for clarity?

**Comment by eabraham** [comment]
:+1: Thanks Mike! Looks good Bert.

**Comment by eabraham** [comment]
On a side note, I can't believe NerdiusMaximus was available.

**Comment by NerdiusMaximus** [comment]
Yeah i got lucky with that one. I've been using it on several platforms.

-M-


On Sun, Mar 22, 2015 at 3:09 PM, eabraham <notifications@github.com> wrote:

> On a side note, I can't believe NerdiusMaximus was available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MakerBar/makerbar.github.io/pull/3#issuecomment-84680459>
> .
>



-- 
Michael Lowry
Senior Research Technician
Orthopaedic Implant Design Laboratory
NYU Hospital for Joint Diseases
Office: (212) - 598-6000 x 6741
Mobile: (201) 787-8633
michael.lowry@nyumc.org
mtl6@njit.edu

**Pull request merged**
